tasks:
  - name: initialize
    before: |
      CAPSULE_BUILDER_VERSION="v0.0.2"
      wget -O - https://raw.githubusercontent.com/bots-garden/capsule-function-builder/${CAPSULE_BUILDER_VERSION}/install-capsule-builder.sh | bash

    init: |
      echo "👋 Hello, Capsule is installed. Have fun 🙂"

ports:
  - port: 3000-25000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - pkief.material-icon-theme
    - aaron-bond.better-comments
    - golang.go
    - PKief.material-icon-theme